# TODO: copied from the output of `tflocal` - to be replaced over time
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  region = "us-east-1"
  endpoints {
    acm = "http://host.docker.internal:4566"
    amplify = "http://host.docker.internal:4566"
    apigateway = "http://host.docker.internal:4566"
    apigatewayv2 = "http://host.docker.internal:4566"
    appconfig = "http://host.docker.internal:4566"
    appflow = "http://host.docker.internal:4566"
    applicationautoscaling = "http://host.docker.internal:4566"
    appsync = "http://host.docker.internal:4566"
    athena = "http://host.docker.internal:4566"
    autoscaling = "http://host.docker.internal:4566"
    backup = "http://host.docker.internal:4566"
    batch = "http://host.docker.internal:4566"
    cloudformation = "http://host.docker.internal:4566"
    cloudfront = "http://host.docker.internal:4566"
    cloudsearch = "http://host.docker.internal:4566"
    cloudtrail = "http://host.docker.internal:4566"
    cloudwatch = "http://host.docker.internal:4566"
    cloudwatchlogs = "http://host.docker.internal:4566"
    codecommit = "http://host.docker.internal:4566"
    cognitoidentity = "http://host.docker.internal:4566"
    cognitoidp = "http://host.docker.internal:4566"
    config = "http://host.docker.internal:4566"
    costexplorer = "http://host.docker.internal:4566"
    docdb = "http://host.docker.internal:4566"
    dynamodb = "http://host.docker.internal:4566"
    ec2 = "http://host.docker.internal:4566"
    ecr = "http://host.docker.internal:4566"
    ecs = "http://host.docker.internal:4566"
    efs = "http://host.docker.internal:4566"
    eks = "http://host.docker.internal:4566"
    elasticache = "http://host.docker.internal:4566"
    elasticbeanstalk = "http://host.docker.internal:4566"
    elb = "http://host.docker.internal:4566"
    elbv2 = "http://host.docker.internal:4566"
    emr = "http://host.docker.internal:4566"
    es = "http://host.docker.internal:4566"
    events = "http://host.docker.internal:4566"
    firehose = "http://host.docker.internal:4566"
    fis = "http://host.docker.internal:4566"
    glacier = "http://host.docker.internal:4566"
    glue = "http://host.docker.internal:4566"
    iam = "http://host.docker.internal:4566"
    iot = "http://host.docker.internal:4566"
    iotanalytics = "http://host.docker.internal:4566"
    iotevents = "http://host.docker.internal:4566"
    kafka = "http://host.docker.internal:4566"
    keyspaces = "http://host.docker.internal:4566"
    kinesis = "http://host.docker.internal:4566"
    kinesisanalytics = "http://host.docker.internal:4566"
    kinesisanalyticsv2 = "http://host.docker.internal:4566"
    kms = "http://host.docker.internal:4566"
    lakeformation = "http://host.docker.internal:4566"
    lambda = "http://host.docker.internal:4566"
    mediaconvert = "http://host.docker.internal:4566"
    mediastore = "http://host.docker.internal:4566"
    mq = "http://host.docker.internal:4566"
    mwaa = "http://mwaa.localhost.localstack.cloud:4566"
    neptune = "http://host.docker.internal:4566"
    opensearch = "http://host.docker.internal:4566"
    organizations = "http://host.docker.internal:4566"
    qldb = "http://host.docker.internal:4566"
    ram = "http://host.docker.internal:4566"
    rds = "http://host.docker.internal:4566"
    redshift = "http://host.docker.internal:4566"
    redshiftdata = "http://host.docker.internal:4566"
    resourcegroups = "http://host.docker.internal:4566"
    resourcegroupstaggingapi = "http://host.docker.internal:4566"
    route53 = "http://host.docker.internal:4566"
    route53domains = "http://host.docker.internal:4566"
    route53resolver = "http://host.docker.internal:4566"
    s3 = "http://s3.localhost.localstack.cloud:4566"
    s3control = "http://host.docker.internal:4566"
    sagemaker = "http://host.docker.internal:4566"
    scheduler = "http://host.docker.internal:4566"
    secretsmanager = "http://host.docker.internal:4566"
    serverlessrepo = "http://host.docker.internal:4566"
    servicediscovery = "http://host.docker.internal:4566"
    ses = "http://host.docker.internal:4566"
    sesv2 = "http://host.docker.internal:4566"
    sns = "http://host.docker.internal:4566"
    sqs = "http://host.docker.internal:4566"
    ssm = "http://host.docker.internal:4566"
    stepfunctions = "http://host.docker.internal:4566"
    sts = "http://host.docker.internal:4566"
    swf = "http://host.docker.internal:4566"
    timestreamwrite = "http://host.docker.internal:4566"
    transcribe = "http://host.docker.internal:4566"
    transfer = "http://host.docker.internal:4566"
    waf = "http://host.docker.internal:4566"
    wafv2 = "http://host.docker.internal:4566"
    xray = "http://host.docker.internal:4566"
 }
}

# resource "aws_s3_bucket" "bucket" {
#   bucket = "test-bucket"
# }

resource "aws_sqs_queue" "test-queue" {
  name = "test-queue"
}
